#!/bin/sh
set -e

mkdir -p /var/log/supervisor

if [ "$1" = "--" ]
then
	envdir /env supervisord -n -c /etc/supervisor/supervisord.conf &
	shift
	envdir /env $@
else
	envdir /env supervisord -n -c /etc/supervisor/supervisord.conf 	
fi